// =============================================================================
// src/core/tools/tool_builder.cpp — create_tool native tool
// =============================================================================
// Scaffolds a new HTTP-template tool as a .cpp file under
// src/core/tools/generated/ (see http_tool_runtime.h for the execution
// model). This does NOT make the tool live — it writes source that only
// takes effect after a rebuild, so a human reviews and compiles it before it
// ever runs. The `tool-builder` agent (agents/tool-builder.yaml) is meant to
// interview the user for all of this tool's fields before calling here.

#include "../tools.h"
#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <regex>
#include <sstream>
#include <vector>

namespace fs = std::filesystem;

namespace {

const std::regex kNameRe(R"(^[a-z][a-z0-9_]{1,40}$)");

// Escapes a string for embedding in a regular (non-raw) C++ string literal.
std::string cpp_escape(const std::string& s) {
    std::string out;
    out.reserve(s.size() + 8);
    for (char c : s) {
        switch (c) {
            case '\\': out += "\\\\"; break;
            case '"':  out += "\\\""; break;
            case '\n': out += "\\n";  break;
            default:   out += c;
        }
    }
    return out;
}

std::string uppercase(std::string s) {
    for (char& c : s) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    return s;
}

bool valid_method(const std::string& m) {
    static const std::vector<std::string> ok = {"GET", "POST", "PUT", "PATCH", "DELETE"};
    return std::find(ok.begin(), ok.end(), m) != ok.end();
}

std::string generate_source(const std::string& name, const std::string& description,
                            const std::string& method, const std::string& url_template,
                            const json& parameters, const json& headers,
                            const std::string& body_template) {
    // Raw string delimiters are capped at 16 chars by the standard, and only
    // need to be unique within this one literal — a fixed delimiter is fine.
    const std::string delim = "SCHEMA";

    std::ostringstream out;
    out << "// Auto-generated by create_tool. Do not hand-edit — ask the tool-builder\n"
        << "// agent to regenerate it instead. Requires `cmake --build` + restart to\n"
        << "// take effect (Funes tools ship with a release, not live at runtime).\n"
        << "#include \"../http_tool_runtime.h\"\n\n"
        << "namespace {\n\n"
        << "void register_" << name << "(ToolRegistry& reg) {\n"
        << "    static const std::map<std::string, std::string> headers = {\n";
    for (auto it = headers.begin(); it != headers.end(); ++it) {
        out << "        {\"" << cpp_escape(it.key()) << "\", \""
            << cpp_escape(it.value().get<std::string>()) << "\"},\n";
    }
    out << "    };\n"
        << "    reg.add({\n"
        << "        \"" << name << "\",\n"
        << "        \"" << cpp_escape(description) << "\",\n"
        << "        json::parse(R\"" << delim << "(\n" << parameters.dump(2) << "\n)"
        << delim << "\"),\n"
        << "        funes::tools::make_http_template_tool(\n"
        << "            \"" << method << "\",\n"
        << "            \"" << cpp_escape(url_template) << "\",\n"
        << "            headers,\n"
        << "            \"" << cpp_escape(body_template) << "\")\n"
        << "    });\n"
        << "}\n\n"
        << "const bool _registered_" << name
        << " = (funes::tools::register_generated(register_" << name << "), true);\n\n"
        << "} // namespace\n";
    return out.str();
}

ToolResult create_tool_handler(const std::string& generated_dir, const json& args, const ToolContext&) {
    if (!args.contains("name") || !args["name"].is_string())
        return {"Missing 'name' argument", true};
    const std::string name = args["name"].get<std::string>();
    if (!std::regex_match(name, kNameRe))
        return {"'name' must be snake_case, start with a letter, and be 2-41 chars "
                "(e.g. 'get_weather')", true};

    if (!args.contains("description") || !args["description"].is_string()
        || args["description"].get<std::string>().empty())
        return {"Missing or empty 'description' argument", true};
    const std::string description = args["description"].get<std::string>();

    std::string method = args.value("method", std::string("GET"));
    method = uppercase(method);
    if (!valid_method(method))
        return {"'method' must be one of GET, POST, PUT, PATCH, DELETE", true};

    if (!args.contains("url_template") || !args["url_template"].is_string())
        return {"Missing 'url_template' argument", true};
    const std::string url_template = args["url_template"].get<std::string>();
    if (url_template.rfind("http://", 0) != 0 && url_template.rfind("https://", 0) != 0)
        return {"'url_template' must start with http:// or https://", true};

    json parameters = args.value("parameters", json::object());
    if (!parameters.is_object())
        return {"'parameters' must be a JSON-schema object (type/properties/required)", true};
    if (!parameters.contains("type"))       parameters["type"] = "object";
    if (!parameters.contains("properties")) parameters["properties"] = json::object();

    json headers = args.value("headers", json::object());
    if (!headers.is_object())
        return {"'headers' must be an object of string header values", true};
    for (auto it = headers.begin(); it != headers.end(); ++it)
        if (!it.value().is_string())
            return {"'headers' values must all be strings (use ${ENV_VAR} for secrets)", true};

    const std::string body_template = args.value("body_template", std::string(""));

    const bool overwrite = args.value("overwrite", false);
    fs::path path = fs::path(generated_dir) / (name + ".cpp");
    if (fs::exists(path) && !overwrite)
        return {"A tool named '" + name + "' already exists at " + path.string() +
                " — pass overwrite=true to replace it.", true};

    std::error_code ec;
    fs::create_directories(generated_dir, ec);

    const std::string source = generate_source(name, description, method, url_template,
                                               parameters, headers, body_template);
    std::ofstream f(path, std::ios::trunc);
    if (!f)
        return {"Could not write " + path.string(), true};
    f << source;
    f.close();

    return {"Scaffolded tool '" + name + "' at " + path.string() +
            ". It will be available once Funes is rebuilt (cmake --build build) "
            "and restarted — this doesn't take effect in the current run."};
}

} // namespace

void register_tool_builder(ToolRegistry& reg, const std::string& generated_dir) {
    reg.add({
        "create_tool",
        "Scaffold a new tool that calls an HTTP endpoint, from structured fields "
        "(not from a live conversation — the tool only becomes available after "
        "Funes is rebuilt and restarted). Gather all fields through conversation "
        "before calling this: what the tool does, the exact endpoint and method, "
        "which inputs it needs (as a JSON-schema 'parameters' object), any static "
        "headers (use ${ENV_VAR_NAME} for secrets, never a literal key), and a "
        "JSON body template for non-GET requests using {param} placeholders "
        "(write them unquoted, e.g. {\"city\": {city}}).",
        {
            {"type", "object"},
            {"properties", {
                {"name",         {{"type", "string"}, {"description", "snake_case tool name, e.g. get_weather"}}},
                {"description",  {{"type", "string"}, {"description", "What the tool does and when to use it"}}},
                {"method",       {{"type", "string"}, {"description", "GET|POST|PUT|PATCH|DELETE, default GET"}}},
                {"url_template", {{"type", "string"}, {"description", "URL with {param} placeholders, e.g. https://api.example.com/v1/weather?city={city}"}}},
                {"parameters",   {{"type", "object"}, {"description", "JSON-schema object describing the tool's arguments"}}},
                {"headers",      {{"type", "object"}, {"description", "Static header values; use ${ENV_VAR} to reference an environment variable"}}},
                {"body_template",{{"type", "string"}, {"description", "JSON body template with unquoted {param} placeholders, for POST/PUT/PATCH"}}},
                {"overwrite",    {{"type", "boolean"}, {"description", "Replace an existing tool of the same name"}}}
            }},
            {"required", json::array({"name", "description", "url_template"})}
        },
        [generated_dir](const json& args, const ToolContext& ctx) {
            return create_tool_handler(generated_dir, args, ctx);
        }
    });
}
